export enum TipoVehiculo {
  FURGONETA,
  COCHE,
  MOTO
}

export enum Provincia{

    ALAVA, ALBACETE, ALICANTE, ALMERIA, ASTURIAS,
		AVILA, BADAJOZ, BARCELONA, BURGOS, CACERES,
		CADIZ, CANTABRIA, CASTELLON, CIUDADREAL, CORDOBA,
		LACORUNA, CUENCA, GERONA, GRANADA, GUADALAJARA,
		GUIPUZCOA, HUELVA, HUESCA, BALEARES, JAEN,
		LEON, LERIDA, LUGO, MADRID, MALAGA,
		MURCIA, NAVARRA, ORENSE, PALENCIA, LASPALMAS,
		PONTEVEDRA, LARIOJA, SALAMANCA, SEGOVIA, SEVILLA,
		SORIA, TARRAGONA, SANTACRUZDETENERIFE, TERUEL, TOLEDO,
		VALENCIA, VALLADOLID, VIZCAYA, ZAMORA, ZARAGOZA
}

export enum Combustible {
		GASOLINA, DIESEL, GLP, ELECTRICO
	}

export enum Transmision{
  MANUAL, AUTOMATICO
}

export enum EtiquetaAmbiental{
   CERO, ECO, C, B, A
}
